// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3HEpUGg87dUD8rGyEvaPdO6p3KKsgzY',
    appId: '1:874766592745:web:f0841aca02cf10cbb81e78',
    messagingSenderId: '874766592745',
    projectId: 'ppmt-db',
    authDomain: 'ppmt-db.firebaseapp.com',
    storageBucket: 'ppmt-db.appspot.com',
    measurementId: 'G-Q639BGP1H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5JfPuDFOsZ-CIIbSIqHHeHQZvmwmMwM',
    appId: '1:874766592745:android:9d9f2b4fdd0a6d11b81e78',
    messagingSenderId: '874766592745',
    projectId: 'ppmt-db',
    storageBucket: 'ppmt-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtEbEyi7DNlnW6UIAXLjeqv_Avb7Kg6_U',
    appId: '1:874766592745:ios:c1b2ed7b9b2c3cb3b81e78',
    messagingSenderId: '874766592745',
    projectId: 'ppmt-db',
    storageBucket: 'ppmt-db.appspot.com',
    iosClientId: '874766592745-s08l5c6pn4f0e8t135jkd9a2ei8sjtt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtEbEyi7DNlnW6UIAXLjeqv_Avb7Kg6_U',
    appId: '1:874766592745:ios:58ba77484b87a377b81e78',
    messagingSenderId: '874766592745',
    projectId: 'ppmt-db',
    storageBucket: 'ppmt-db.appspot.com',
    iosClientId: '874766592745-1piabauvkljrr5lui9omi7fopcpb8p28.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppmt.RunnerTests',
  );
}
